### ISSUE TITLE
wounder if i could use my own request? like axios

### ISSUE THREAD

**Issue by downerxl** [wenzhixin/element-table#3]

**Comment by CuiYuXi** [comment]
Is that right?
https://element.bootstrap-table.com/examples/#/options/table-ajax/view-source

**Comment by wenzhixin** [comment]
Yes, you can use `ajax` option to do this.

**Comment by downerxl** [comment]
> Is that right?
> https://element.bootstrap-table.com/examples/#/options/table-ajax/view-source

that's it,let me try.thanks!
